spring:
  datasource:
    url: jdbc:mysql://192.168.99.100/houtai?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 8000   #  配置启动端口号
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: stu.lkh.system.infra.dataobject
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    stu:
      lkh:
        system:
          infra:
            mapper: debug


#  mybatis.mapper-locations = classpath:mapper/*Mapper.xml
#  mybatis.config-location = classpath:mapper/config/sqlMapConfig.xml
#  mybatis.type-aliases-package = cn.qlq.bean
#配置数据库
